name:                type-inferencing-4tb3
version:             0.1.0.0
github:              "tanyabouman/type-inferencing-4tb3"
license:             BSD3
author:              "Emily Ashworth, Tanya Bouman, Tonye Fiberesima"
maintainer:          "tanyabouman@gmail.com"
copyright:           "2018 Emily Ashworth, Tanya Bouman, Tonye Fiberesima"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Group project for CS4TB3: Compilers and Syntax-Based Tools
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/tanyabouman/type-inferencing-4tb3#readme>

dependencies:
- base >= 4.7 && < 5
- containers

library:
  source-dirs: src

executables:
  type-inferencing-4tb3-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - type-inferencing-4tb3

