# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# copied jobs section from
# https://github.com/CircleCI-Public/circleci-demo-haskell/blob/master/.circleci/config.yml
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts
    steps:
      - checkout
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - cci-demo-haskell-v2-{{ checksum "package.yaml" }}
      - run:
          name: Resolve/Update Dependencies
          command: stack setup
      - run:
          name: Run tests
          command: stack test
      - run:
          name: Install executable
          command: stack install
      - save_cache:
          name: Cache Dependencies
          key: cci-demo-haskell-v2-{{ checksum "package.yaml" }}
          paths:
            - ".stack-work"
            - "/root/.stack"
      - store_artifacts: # upload build artifact for display in CircleCi
          path: ~/.local/bin/circleci-demo-haskell-exe
          destination: circleci-demo-haskell-exe
